const { playerstats } = require('../models');

const playerstatsData = [
    {
        firstName: "Lebron",
        lastName: "James",
        Points: 25,
        rebounds: 10,
        assists: 10,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Anthony",
        lastName: "Davis",
        Points: 20,
        rebounds: 10,
        assists: 5,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "James",
        lastName: "Harden",
        Points: 30,
        rebounds: 5,
        assists: 10,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Kevin",
        lastName: "Durant",
        Points: 25,
        rebounds: 10,
        assists: 10,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Kyrie",
        lastName: "Irving",
        Points: 20,
        rebounds: 10,
        assists: 5,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Stephen",
        lastName: "Curry",
        Points: 30,
        rebounds: 5,
        assists: 10,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Klay",
        lastName: "Thompson",
        Points: 25,
        rebounds: 10,
        assists: 10,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },  
    {
        firstName: "Draymond",
        lastName: "Green",
        Points: 20,
        rebounds: 10,
        assists: 5,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "kawhi",
        lastName: "Leonard",
        Points: 30,
        rebounds: 5,
        assists: 10,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Paul",
        lastName: "George",
        Points: 25,
        rebounds: 10,
        assists: 10,
        steals: 2,
        turnovers: 5,
        blocks: 1,
        personalFouls: 2,
    },
    ];

    const seedPlayerstats = () => playerstats.bulkCreate(playerstatsData);
    module.exports = seedPlayerstats;