const { player } = require('../models');

const playerData = [
    {
        name: "Lebron James",
        position: "SF",
        team: "Lakers",
        age: 36,
        height: "6'8",
        weight: 250,
        college: "St. Vincent-St. Mary HS",
    },
    {
        name: "Anthony Davis",
        position: "PF",
        team: "Lakers",
        age: 27,
        height: "6'10",
        weight: 253,
        college: "Kentucky",
    },
    {
        name: "James Harden",
        position: "SG",
        team: "Nets",
        age: 31,
        height: "6'5",
        weight: 220,
        college: "Arizona State",
    },
    {
        name: "Kevin Durant",
        position: "SF",
        team: "Nets",
        age: 32,
        height: "6'9",
        weight: 240,
        college: "Texas",
    },
    {
        name: "Kyrie Irving",
        position: "PG",
        team: "Nets",
        age: 29,
        height: "6'3",
        weight: 193,
        college: "Duke",
    },
    {
        name: "Stephen Curry",
        position: "PG",
        team: "Warriors",
        age: 33,
        height: "6'3",
        weight: 190,
        college: "Davidson",
    },
    {
        name: "Klay Thompson",
        position: "SG",
        team: "Warriors",
        age: 32,
        height: "6'7",
        weight: 215,
        college: "Washington State",
    },
    {
        name: "Draymond Green",
        position: "PF",
        team: "Warriors",
        age: 32,
        height: "6'7",
        weight: 230,
        college: "Michigan State",
    },
    {
        name: "Kawhi Leonard",
        position: "SF",
        team: "Clippers",
        age: 30,
        height: "6'7",
        weight: 230,
        college: "San Diego State",
    },
    {
        name: "Paul George",
        position: "SF",
        team: "Clippers",
        age: 30,
        height: "6'9",
        weight: 220,
        college: "Fresno State",
    },
];

const seedPlayers = () => player.bulkCreate(playerData);
module.exports = seedPlayers;