const { playerstats } = require('../models');

const playerstatsData = [
    {
        firstName: "Lebron",
        lastName: "James", 
        points: 25,
        rebounds: 10,
        assists: 10,
        steals: 2,
        turnovers: 3,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Anthony",
        lastName: "Davis",
        points: 30,
        rebounds: 12,
        assists: 5,
        steals: 1,
        turnovers: 2,
        blocks: 3,
        personalFouls: 1,
    },
    {
        firstName: "James",
        lastName: "Harden",
        points: 35,
        rebounds: 5,
        assists: 10,
        steals: 2,
        turnovers: 4,
        blocks: 0,
        personalFouls: 3,
    },
    {
        firstName: "Kevin",
        lastName: "Durant",
        points: 40,
        rebounds: 8,
        assists: 5,
        steals: 1,
        turnovers: 3,
        blocks: 2,
        personalFouls: 2,
    },
    {
        firstName: "Kyrie",
        lastName: "Irving",
        points: 30,
        rebounds: 5,
        assists: 10,
        steals: 2,
        turnovers: 3,
        blocks: 0,
        personalFouls: 2,
    },
    {
        firstName: "Stephen",
        lastName: "Curry",
        points: 35,
        rebounds: 5,
        assists: 10,
        steals: 2,
        turnovers: 3,
        blocks: 0,
        personalFouls: 2,
    },
    {
        firstName: "Klay",
        lastName: "Thompson",
        points: 30,
        rebounds: 5,
        assists: 5,
        steals: 2,
        turnovers: 3,
        blocks: 0,
        personalFouls: 2,
    },
    {
        firstName: "Draymond",
        lastName: "Green",
        points: 15,
        rebounds: 10,
        assists: 10,
        steals: 2,
        turnovers: 3,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "kawhi",
        lastName: "Leonard",
        points: 30,
        rebounds: 10,
        assists: 5,
        steals: 2,
        turnovers: 3,
        blocks: 1,
        personalFouls: 2,
    },
    {
        firstName: "Paul",
        lastName: "George",
        points: 30,
        rebounds: 10,
        assists: 5,

        steals: 2,
        turnovers: 3,
        blocks: 1,
        personalFouls: 2,
    },
]

const seedPlayerstats = () => playerstats.bulkCreate(playerstatsData);
module.exports = seedPlayerstats;
